### ISSUE TITLE
Handle lost-connect situation

### ISSUE THREAD

**Issue by dmalikov** [dmalikov/loh#12]
Now loh-ng dies if there are no connection to last.fm.

`lohd: getAddrInfo: does not exist (Name or service not known)`

**Comment by supki** [comment]
Interesting.

**Comment by supki** [comment]
Oh, yes, that's an oversight. Despite the fact that `runJobs` is ran in separate thread it still can irrecoverably die on lastfm failures. `loh` itself (as a main process) is still online anyway?

**Comment by supki** [comment]
I'm going to take a look at that issue tonight if you don't have plans to do it yourself.

**Comment by dmalikov** [comment]
Sure, go ahead

**Comment by supki** [comment]
Here. Please check if it fixed an issue.
