### ISSUE TITLE
Move to scrobblers package?

### ISSUE THREAD

**Issue by supki** [dmalikov/loh#13]
`scrobblers` provides scrobbling layer (sophisticated enough to be used for `loh` purposes). What's missing is nice user interface for using it with multiple players in parallel, that's what loh may provide on top of `scrobblers`

**Comment by supki** [comment]
That would also solve #7 for free

**Comment by dmalikov** [comment]
I'm not familiar with functionality that `scrobblers` provides at now, but it sounds reasonable.

**Comment by supki** [comment]
You should take a look at [README](https://github.com/supki/scrobblers/blob/master/README.md) ! It describes what you can do with `scrobblers` fully.

**Comment by supki** [comment]
loh has been irrelevant for a long time, closing.

**Comment by dmalikov** [comment]
:sob: :sob: :sob:
