### ISSUE TITLE
Document lohd protocol, please

### ISSUE THREAD

**Issue by supki** [dmalikov/loh#8]
Someone might want to write non-standard loh client (with GUI, for example).
It would require protocol documentation, I don't think it's convenient to look lohd sources up for that.

**Comment by dmalikov** [comment]
Take a look, please. 
https://github.com/dmalikov/loh/wiki/Lohd-specification

**Comment by supki** [comment]
Could lfmConfig JSON encoding be flattened?

**Comment by dmalikov** [comment]
Maybe it could be done with some wrapper types over `haskell-liblastfm` types.

**Comment by supki** [comment]
Thanks!

**Comment by dmalikov** [comment]
You are welcome!

**Comment by supki** [comment]
Why do we need `totalSec` and `currentSec` fields?
`totalSec` is apparently length of the track for now playing status?

**Comment by supki** [comment]
Also, can you please rename
`trackInfo` ⇒ `track`
`totalSec` ⇒ `length`
`track` ⇒ `title`
`currentSec` ⇒ `currentTime` (if that is needed actually)
`lfmConfig` ⇒ `auth`

**Comment by dmalikov** [comment]
Seems like `currentSec` is redundant.
`totalSec` is optional for now playing status and scrobble, btw,

**Comment by dmalikov** [comment]
It would be better? 

```
{
    "track": {
        "album": null,
        "title": "Sqoocka",
        "length": null,
        "artist": "Дмитрий Маликов"
    },
    "type": "Scrobble",
    "auth": {
        "secret": "c",
        "apiKey": "a",
        "sessionKey": "b"
    }
}
```

**Comment by supki** [comment]
That's what I wanted.
